#pragma once
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
namespace WhiplashTags
{
	// States
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WallFlattened);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Peeking);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HoldingBreath);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	// Abilities
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Shoot);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Reload);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Melee);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Dodge);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Crouch)
	// Detection
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Detection_Sound);
}