#pragma once
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
namespace WhiplashTags
{
	// States
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WallFlattened);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Peeking);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HoldingBreath);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ADS);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Firing);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WeaponEquipped);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Pistol);
	//WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle); // for future 

	// Abilities
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Shoot);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Reload);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Melee);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Dodge);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Crouch)
	// Detection
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Detection_Sound);
	
	//Modifiers
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modifier_Stamina_Drain);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modifier_Stamina_Regen);
	
	//DamageZones
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageZone_Head);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageZone_Torso);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageZone_Limbs);
	
	//Phys.Mats 
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalMaterial_Concrete);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalMaterial_Metal);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalMaterial_Wood);
	//WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalMaterial_Carpet);
	WHIPLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalMaterial_Dirt);
	
	
}